#!/usr/bin/python3

import sys
import math

def factorize_numbers(file_path):
    with open(file_path, 'r') as file:
        for line in file:
            number = int(line)
            factor = None
            for i in range(2, int(math.sqrt(number)) + 1):
                if number % i == 0:
                    factor = i
                    break
            if factor is not None:
                print(f"{number}={number // factor}*{factor}")
            else:
                print(f"{number}=Prime")

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: factors <file>")
        sys.exit(1)
    factorize_numbers(sys.argv[1])