#!/usr/bin/python3

import sys

def factorize_numbers(file_path):
    with open(file_path, 'r') as file:
        for line in file:
            number = int(line)
            factor = factorize(number)
            print(f"{number}={number // factor}*{factor}")

def factorize(n):
    if n <= 1:
        return None

    for i in range(2, n):
        if n % i == 0:
            return i

    return n

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: factors <file>")
        sys.exit(1)
    factorize_numbers(sys.argv[1])